"""Versioned October wire shape and signed selection; synthetic I/O only.

records.json is generated by exact Core getters, not a hand-edited historical
capture. Full Core startup and transport acceptance remain a separate lane.
"""
from copy import deepcopy
from datetime import timedelta
import hashlib
import json
from pathlib import Path
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / 'hass_mcp_engineering_beta'), str(ROOT / 'tests')]
from core_registry_fixtures import CoreSigner, core_entry, core_revocation, NOW
from ha_mcp_engineering.ha_core_readmission.device_registry import (
    DeviceRegistrySchema, MAX_DEVICE_RECORD_BYTES, MAX_DEVICE_RECORDS,
    assess_device_registry, assess_device_entity_semantics,
    assess_ha_mcp_device_projection,
)
from ha_mcp_engineering.ha_core_readmission.probe_profiles import (
    CHILD_DEVICE_NAME_PARTS_PROBE_PROFILE as OCTOBER,
    CHILD_DEVICE_PROBE_PROFILE as SEPTEMBER,
    LEGACY_PROBE_PROFILE, compiled_probe_profile, known_probe_profile,
)
from ha_mcp_engineering.ha_core_readmission.profiles import (
    CORE_RUNTIME_CAPABILITY_PROFILES, compiled_exact_authority,
)
from ha_mcp_engineering.ha_core_readmission.models import CORE_IDENTITY
from ha_mcp_engineering.ha_core_readmission.registry import CoreReleaseRegistry
from ha_mcp_engineering.ha_core_readmission.routes import delegated_provider_compatibility
from ha_mcp_engineering.ha_core_readmission.runtime import CoreRuntime
from ha_mcp_engineering.ha_core_readmission.source import capability_evidence_for_probes

FIXTURES = ROOT / 'tests/fixtures/core_2026_10_device_registry'
SCHEMA = DeviceRegistrySchema.CHILD_DEVICE_NAME_PARTS
DEVICE_CAPABILITIES = {'core.direct_device_registry_read',
                       'core.delegated_device_effective_area',
                       'core.dependency_helper_planning'}


def fixture():
    return json.loads((FIXTURES / 'records.json').read_text())


def projection():
    return {'devices': [
        {'device_id': 'parent-area', 'parent_device_id': None, 'effective_area_id': 'synthetic-area'},
        {'device_id': 'parent-none', 'parent_device_id': None, 'effective_area_id': None},
        {'device_id': 'child-own', 'parent_device_id': 'parent-none', 'effective_area_id': 'synthetic-other-area'},
        {'device_id': 'child-inherit', 'parent_device_id': 'parent-area', 'effective_area_id': 'synthetic-area'},
        {'device_id': 'child-none', 'parent_device_id': 'parent-none', 'effective_area_id': None},
    ], 'entities': [
        {'entity_id': 'sensor.synthetic_inherited', 'effective_area_id': 'synthetic-area'},
        {'entity_id': 'sensor.synthetic_own', 'effective_area_id': 'synthetic-other-area'},
        {'entity_id': 'sensor.synthetic_override', 'effective_area_id': 'synthetic-override'},
        {'entity_id': 'sensor.synthetic_unassigned', 'effective_area_id': None},
    ]}


def probe_inputs(profile, records=None, version='2026.10.0'):
    data = fixture() if records is None else records
    return dict(version=version, probe_profile=profile,
        include_typed_operations=True, include_integration_inspection=True,
        include_automation_baseline=True,
        rest_config={'version':version}, websocket_config={'version':version},
        states=[{'entity_id':'sensor.synthetic','state':'ready','attributes':{}}],
        services=[{'domain':'input_boolean','services':{}}],
        configuration_validation={'result':'valid','errors':None,'warnings':None},
        websocket_results={'areas':[], 'floors':[], 'labels':[],
            'entities':data['entities'], 'devices':data['devices'],
            'dashboards':[{'url_path':'synthetic-dashboard'}],
            'automation':{'id':'synthetic'}, 'dashboard':{'views':[]}, 'trace_list':[],
            'trace_get':{'_ha_mcp_engineering_expected_probe_error':'not_found'}})


class OctoberDeviceShapeTests(unittest.TestCase):
    def setUp(self):
        self.data = fixture()
        self.records = self.data['devices']

    def test_fixture_hash_and_exact_source_provenance(self):
        p = json.loads((FIXTURES / 'provenance.json').read_text())
        self.assertEqual(p['records_sha256'], hashlib.sha256((FIXTURES/'records.json').read_bytes()).hexdigest())
        self.assertEqual(p['source_commit'], '6a811d3359c7b2076dc9e1cf900843a129c044af')
        self.assertEqual(p['archive_sha256'], '96778e8c130c16e86619e82741d308e41c76d2963da649f0748f7b51fb9703b9')
        self.assertFalse(p['full_core_execution'])
        self.assertEqual(set(p['getters']), {'DeviceEntry.dict_repr', 'DeviceEntry.next_name_part',
                                             'ChildDeviceEntry.dict_repr', 'ChildDeviceEntry.next_name_part'})

    def test_exact_october_records_pass_selected_schema_without_mutation(self):
        before = deepcopy(self.records)
        result = assess_device_registry(self.records, schema=SCHEMA)
        self.assertTrue(result.complete)
        self.assertEqual((result.record_count, result.child_count), (5, 3))
        self.assertEqual(self.records, before)

    def test_default_and_september_profile_do_not_admit_october_shape(self):
        self.assertFalse(assess_device_registry(self.records).complete)
        self.assertFalse(assess_device_registry(self.records, schema=SEPTEMBER.device_registry_schema).complete)
        ids = {e['capability_id'] for e in capability_evidence_for_probes(**probe_inputs(SEPTEMBER))}
        self.assertEqual(len(ids), 18)
        self.assertTrue(DEVICE_CAPABILITIES.isdisjoint(ids))

    def test_october_profile_restores_all_required_probe_evidence(self):
        ids = {e['capability_id'] for e in capability_evidence_for_probes(**probe_inputs(OCTOBER))}
        self.assertEqual(ids, {p.capability_id for p in CORE_RUNTIME_CAPABILITY_PROFILES})

    def test_september_records_still_pass_default_but_not_october(self):
        old = json.loads((ROOT/'tests/fixtures/ha_core_2026_9_device_registry.json').read_text())
        self.assertTrue(assess_device_registry(old['devices']).complete)
        self.assertFalse(assess_device_registry(old['devices'], schema=SCHEMA).complete)
        ids = {e['capability_id'] for e in capability_evidence_for_probes(**probe_inputs(OCTOBER, old))}
        self.assertTrue(DEVICE_CAPABILITIES.isdisjoint(ids))

    def test_mixed_wire_generations_refused(self):
        del self.records[-1]['next_name_part']
        for schema in (SCHEMA, SEPTEMBER.device_registry_schema):
            self.assertFalse(assess_device_registry(self.records, schema=schema).complete)

    def test_every_required_member_and_unknown_extra_refused(self):
        for i, item in enumerate(self.records):
            for field in item:
                with self.subTest(record=i, missing=field):
                    data = deepcopy(self.records); del data[i][field]
                    self.assertFalse(assess_device_registry(data, schema=SCHEMA).complete)
            data = deepcopy(self.records); data[i]['unreviewed'] = None
            self.assertFalse(assess_device_registry(data, schema=SCHEMA).complete)

    def test_name_part_must_match_explicit_area_and_parent(self):
        for i, item in enumerate(self.records):
            for value in (None, 'area', 'parent_device', 'device', '', True, 1, {}, []):
                if value == item['next_name_part']:
                    continue
                with self.subTest(record=i, value_type=type(value).__name__):
                    data = deepcopy(self.records); data[i]['next_name_part'] = value
                    self.assertEqual(assess_device_registry(data, schema=SCHEMA).reason_code,
                                     'device_name_part_malformed')

    def test_unknown_schema_refused_even_for_empty_inventory(self):
        for schema in (None, 'child-device-name-parts-v1', 'future', True):
            self.assertEqual(assess_device_registry([], schema=schema).reason_code,
                             'device_registry_schema_unknown')

    def test_duplicate_orphan_cycle_and_child_chain_refused(self):
        cases = []
        data = deepcopy(self.records); data.append(deepcopy(data[0])); cases.append(data)
        data = deepcopy(self.records); data[-1]['parent_device_id'] = 'missing'; cases.append(data)
        data = deepcopy(self.records); data[-1]['parent_device_id'] = data[-1]['id']; cases.append(data)
        data = deepcopy(self.records); data[-1]['parent_device_id'] = data[2]['id']; cases.append(data)
        for data in cases:
            self.assertFalse(assess_device_registry(data, schema=SCHEMA).complete)

    def test_invalid_id_area_parent_and_json_refused(self):
        for i, field, value in ((0,'id','x'*129), (0,'area_id',False),
                                (3,'parent_device_id',''), (0,'created_at',float('nan')),
                                (0,'connections', [['mac', 17]])):
            data = deepcopy(self.records); data[i][field] = value
            self.assertFalse(assess_device_registry(data, schema=SCHEMA).complete)

    def test_record_and_byte_limits_preserved(self):
        self.assertEqual(assess_device_registry([{}]*(MAX_DEVICE_RECORDS+1), schema=SCHEMA).reason_code,
                         'device_registry_oversized_or_invalid')
        self.records[0]['name'] = 'X' * MAX_DEVICE_RECORD_BYTES
        self.assertEqual(assess_device_registry(self.records, schema=SCHEMA).reason_code,
                         'device_registry_oversized_or_invalid')

    def test_metadata_never_changes_effective_area_fingerprint(self):
        # This is a transformation control, not a claim of a historical capture.
        old_shape = [{k:v for k,v in r.items() if k!='next_name_part'} for r in self.records]
        new = assess_device_registry(self.records, schema=SCHEMA)
        old = assess_device_registry(old_shape)
        self.assertTrue(new.complete and old.complete)
        self.assertEqual(new.semantic_fingerprint, old.semantic_fingerprint)

    def test_entity_inheritance_override_and_missing_reference(self):
        entities = self.data['entities']
        self.assertTrue(assess_device_entity_semantics(self.records, entities, schema=SCHEMA).complete)
        self.assertFalse(assess_device_entity_semantics(self.records, entities).complete)
        entities[0]['device_id'] = 'missing'
        self.assertEqual(assess_device_entity_semantics(self.records, entities, schema=SCHEMA).reason_code,
                         'entity_device_missing')

    def test_delegated_projection_preserves_parent_and_effective_area(self):
        expected = projection()
        self.assertTrue(assess_ha_mcp_device_projection(self.records, self.data['entities'], expected, schema=SCHEMA).complete)
        self.assertFalse(assess_ha_mcp_device_projection(self.records, self.data['entities'], expected).complete)
        for group, index, field, value in [('devices',3,'effective_area_id',None),
                                          ('devices',3,'parent_device_id',None),
                                          ('entities',2,'effective_area_id','synthetic-area')]:
            wrong = deepcopy(expected); wrong[group][index][field] = value
            self.assertFalse(assess_ha_mcp_device_projection(self.records, self.data['entities'], wrong, schema=SCHEMA).complete)

    def test_existing_fingerprints_preserved_new_profile_closed(self):
        # Independently read from unchanged c4168a6 in the assessment checkout.
        self.assertEqual(LEGACY_PROBE_PROFILE.contract_fingerprint,
                         'sha256:017d6f12f0363f71385cece5bd72f9f8ddfc9adfec8787026411fe9933d1115a')
        self.assertEqual(SEPTEMBER.contract_fingerprint,
                         'sha256:c2706d08f75ecef2a7d37265df6eddb03f95bc97d87a08d8632f861202594f46')
        self.assertIs(known_probe_profile(OCTOBER.profile_id, OCTOBER.contract_fingerprint), OCTOBER)
        self.assertIsNone(known_probe_profile(OCTOBER.profile_id, SEPTEMBER.contract_fingerprint))
        self.assertIsNone(compiled_probe_profile('2026.10.0'))
        self.assertEqual(compiled_exact_authority('2026.10.0'), ())

    def test_october_provider_binding_only_admits_exact_reviewed_adapters(self):
        for version in ('8.5.0', '8.6.0', '8.4.3', '8.6.1', None):
            ok, reason = delegated_provider_compatibility(tool_name='ha_get_device',
                core_version='2026.10.0', adapter_version=version, probe_profile=OCTOBER)
            self.assertEqual(ok, version in {'8.5.0', '8.6.0'})
            self.assertEqual(reason, None if ok else 'ha_mcp_child_device_contract_unproven')


class OctoberSignedSelectionTests(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.tmp = tempfile.TemporaryDirectory(); self.addCleanup(self.tmp.cleanup)
        self.signer = CoreSigner()
        self.entry = core_entry('2026.10.0', typed_operations=True)
        self.entry.update(probe_profile_id=OCTOBER.profile_id,
                          probe_profile_sha256=OCTOBER.contract_fingerprint,
                          capabilities=[{k:p.to_mapping()[k] for k in (
                              'capability_id','profile_id','profile_version','adapter_id','contract_fingerprint')}
                              for p in CORE_RUNTIME_CAPABILITY_PROFILES])
        self.now = NOW
        self.raw = None
        async def fetch(*_args):
            if self.raw is None:
                raise OSError('Synthetic authority unavailable')
            return self.raw
        self.registry = CoreReleaseRegistry(enabled=True, public_key=self.signer.public_key_base64,
            cache_path=Path(self.tmp.name)/'registry.json', fetcher=fetch, now=lambda:self.now)
        self.core = CoreRuntime()
        outer = self
        class Source:
            async def capture_core_snapshot(self):
                version = '2026.10.0'
                evidence = capability_evidence_for_probes(**probe_inputs(outer.registry.probe_profile_for(version)))
                return {'identity':CORE_IDENTITY,'connected':True,'authenticated':True,
                    'session_id':'synthetic-october-core', 'rest_config':{'version':version},
                    'websocket_auth_ok':{'type':'auth_ok','ha_version':version},
                    'websocket_get_config':{'version':version}, 'capability_evidence':evidence}
        self.core.configure(object(), source=Source(), release_registry=self.registry)

    async def publish(self, entry=None, revocations=()):
        self.raw = self.signer.journal_raw(
            entries=[] if revocations else [self.entry if entry is None else entry],
            revocations=list(revocations),
            generated_at=NOW,
        )
        self.assertTrue(await self.registry.refresh())
        return await self.core.reconcile_once('synthetic_october_registry')

    async def test_observation_alone_withholds_then_exact_signed_profile_admits(self):
        before = await self.core.reconcile_once('synthetic_missing_authority')
        self.assertEqual(before['compatible_count'], 0)
        after = await self.publish()
        self.assertEqual(after['compatible_count'], 21)
        self.assertIs(self.registry.probe_profile_for('2026.10.0'), OCTOBER)
        self.assertEqual(after['fallback_count'], 0)

    async def test_signed_old_schema_does_not_accept_new_records(self):
        entry = deepcopy(self.entry)
        entry.update(probe_profile_id=SEPTEMBER.profile_id, probe_profile_sha256=SEPTEMBER.contract_fingerprint)
        health = await self.publish(entry)
        self.assertEqual(health['compatible_count'], 18)
        for capability in DEVICE_CAPABILITIES:
            self.assertIsNone(self.core.acquire((capability,)))

    async def test_wrong_profile_fingerprint_withholds_all(self):
        self.entry['probe_profile_sha256'] = SEPTEMBER.contract_fingerprint
        health = await self.publish()
        self.assertEqual(health['compatible_count'], 0)
        self.assertIsNone(self.registry.probe_profile_for('2026.10.0'))

    async def test_signed_unknown_profile_withholds_all(self):
        self.entry['probe_profile_id'] = 'unreviewed-probe'
        health = await self.publish()
        self.assertEqual(health['compatible_count'], 0)

    async def test_other_version_cannot_authorize_october(self):
        self.entry['version'] = '2026.10.1'
        health = await self.publish()
        self.assertEqual(health['compatible_count'], 0)

    async def test_expired_registry_withdraws_october(self):
        self.assertEqual((await self.publish())['compatible_count'], 21)
        self.now = NOW + timedelta(days=400)
        self.assertIsNone(self.registry.probe_profile_for('2026.10.0'))
        self.assertEqual((await self.core.reconcile_once('synthetic_expired'))['compatible_count'], 0)

    async def test_revocation_prevents_october_admission(self):
        health = await self.publish(revocations=[core_revocation('2026.10.0')])
        self.assertEqual(health['compatible_count'], 0)
        self.assertIsNone(self.registry.probe_profile_for('2026.10.0'))
