"""Home Assistant Core capability-scoped readmission contracts and runtime."""

from .coordinator import (
    CoreGenerationAllocator,
    CoreReadmissionCoordinator,
    CoreReconciliationAttempt,
    LocalCoreGenerationAllocator,
)
from .device_registry import (
    DeviceRegistryAssessment,
    assess_device_registry,
    assess_device_entity_semantics,
    assess_ha_mcp_device_projection,
)
from .models import (
    CORE_IDENTITY,
    CORE_PROTOCOL,
    SURFACE,
    CoreAuthoritySelection,
    CoreAuthoritySource,
    CoreAuthorityStatus,
    CoreCapabilityClass,
    CoreCapabilityDecision,
    CoreCapabilityEvidence,
    CoreCapabilityProfile,
    CoreDecisionGeneration,
    CoreDispatchCommit,
    CoreDisposition,
    CoreObservation,
    CoreReadmissionError,
    CoreReconciliationResult,
    CoreRouteLease,
    canonical_json,
    fingerprint,
)
from .observation import (
    CoreObservationCollector,
    CoreSnapshotSource,
    stable_observation,
)
from .profiles import (
    CORE_2026_9_1_AUTHORITY,
    CORE_2026_9_AUTHORITY,
    CORE_2026_9_RELEASE_AUTHORITIES,
    CORE_CAPABILITY_PROFILES,
    SUPPORTED_CORE_RELEASES,
    compiled_exact_authority,
)
from .routes import (
    CORE_2026_9_DEVICE_ADAPTER_RELEASES,
    CORE_2026_9_RELEASES,
    DELEGATED_CORE_REQUIREMENTS,
    DEVICE_DEPENDENT_DELEGATED_TOOLS,
    STATIC_TOOL_CORE_REQUIREMENTS,
    delegated_requirements,
    delegated_provider_compatibility,
    f3_requirements,
    static_tool_requirements,
)
from .runtime import CORE_READMISSION, CoreRouteAuthority, CoreRuntime


__all__ = [
    "CORE_2026_9_1_AUTHORITY",
    "CORE_2026_9_AUTHORITY",
    "CORE_2026_9_DEVICE_ADAPTER_RELEASES",
    "CORE_2026_9_RELEASES",
    "CORE_2026_9_RELEASE_AUTHORITIES",
    "CORE_CAPABILITY_PROFILES",
    "CORE_IDENTITY",
    "CORE_PROTOCOL",
    "CORE_READMISSION",
    "DELEGATED_CORE_REQUIREMENTS",
    "DEVICE_DEPENDENT_DELEGATED_TOOLS",
    "SUPPORTED_CORE_RELEASES",
    "STATIC_TOOL_CORE_REQUIREMENTS",
    "SURFACE",
    "CoreAuthoritySelection",
    "CoreAuthoritySource",
    "CoreAuthorityStatus",
    "CoreCapabilityClass",
    "CoreCapabilityDecision",
    "CoreCapabilityEvidence",
    "CoreCapabilityProfile",
    "CoreDecisionGeneration",
    "CoreDispatchCommit",
    "CoreDisposition",
    "CoreGenerationAllocator",
    "CoreObservation",
    "CoreObservationCollector",
    "CoreReadmissionCoordinator",
    "CoreReadmissionError",
    "CoreReconciliationAttempt",
    "CoreReconciliationResult",
    "CoreRouteAuthority",
    "CoreRouteLease",
    "CoreRuntime",
    "CoreSnapshotSource",
    "DeviceRegistryAssessment",
    "LocalCoreGenerationAllocator",
    "assess_device_registry",
    "assess_device_entity_semantics",
    "assess_ha_mcp_device_projection",
    "canonical_json",
    "compiled_exact_authority",
    "delegated_requirements",
    "delegated_provider_compatibility",
    "f3_requirements",
    "fingerprint",
    "stable_observation",
    "static_tool_requirements",
]
